# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3ff127fe6a7acc95656878435994cbd76ae1cc5319c56acaddb694ec7ac363d8a83b6b341611b878d8a486bdd581730ca812b614445d194c0fcfc03cb2bfefd

test:
  secret_key_base: 186c15b975ae03cd0704ee5905a64f8368d50ef2b49592b3c25d540e6e181c046b8c9001fecaeff211a659decdb31d8488cb8bca5eb0c2a6c0824412e331d268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
